[package]
name = "disk"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/disk.rs"
crate-type = ["staticlib"]

[dependencies]
bitflags = "1.3.2"
m3 = { path = "../../libs/rust/m3" }
pci = { path = "../../libs/rust/pci" }
