[package]
name = "smoltcploop"
version = "0.1.0"
edition = "2018"

[lib]
path = "../../server/smoltcp_server/src/loop_main.rs"
crate-type = ["staticlib"]

[dependencies]
m3 = { path = "../../libs/rust/m3" }
local_smoltcp = { path = "../../libs/local_smoltcp", default-features = true }
